### ISSUE TITLE
Roadmap for HIP support

### ISSUE THREAD

**Issue by Rombur** [kokkos/kokkos#2309]
Below are the tasks planned to support HIP in Kokkos and the milestones associated with each task.
- [ ] atomic (release 3.1)
- [ ] View (release 3.3)
- [ ] policy: 
  - [ ] range  (release 3.1)
  - [ ] MD range (release 3.2)
  - [ ] team (release 3.4)
- [ ] parallel_for  (release 3.1)
- [ ] parallel_reduce (release 3.2)
- [ ] parallel_scan (release 3.3)
- [ ] task  (release 3.4)
- [ ] random-access trait  (release 3.4)

**Comment by crtrott** [comment]
Why View in 3.3 and not in 3.2 with MD range?

**Comment by Rombur** [comment]
All these items have been completed
