### ISSUE TITLE
Kokkos Release 3.5

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4046]
This initial comment is a first pass to track outstanding issues blocking release:

- [x] #3936 Intel build failures - funky hang when compiling unit tests that prevents nightlies from completing compilation step, would likely pose same problem with PR of Kokkos snapshot to Trilinos

- [x] #3907 xl/16.1.1 compilation errors - a temporary fix was patched to the release-candidate-3.4.0 (PR #3923), a potential preferred approach was drafted in #3924 which at the time awaited completion of PR #3832 with more AnalyzePolicy cleanup

- [x] https://github.com/kokkos/kokkos/pull/3962 mathematical_functions_power_functions issue with gcc on Power{8,9} arches, for release-candidate-3.4.0 test was disabled for Power arch, need to propagate to develop or pose alternative solution

**Comment by ndellingwood** [comment]
@ajpowelsnl shouldn't this stay open until release?

**Comment by masterleinad** [comment]
Not all issues have been addressed.

**Comment by ndellingwood** [comment]
Updating to add a couple more items:

- [ ] Remaining desul related failures to resolve in #4136 
       - XL linker issues: https://github.com/kokkos/kokkos/issues/4136#issuecomment-873200530
       - Intel/17.0.1 unit test failures (scatterview) https://github.com/kokkos/kokkos/issues/4136#issuecomment-876579546

- [ ] Intel/17.0.4 nightly test failure #4113: illegal instruction in random num gen tests - possibly related to intel/17.0.1 issue, @ndellingwood assigned

- [ ] Trilinos Nightly Build error with Serial build and intel/18: internal error compiling Intrepid2 StructuredIntegrationTests.cpp tests - @ndellingwood looking into this
