### ISSUE TITLE
[do not close] NGA/task 4: tracking performance testing task

### ISSUE THREAD

**Issue by fnrizzi** [kokkos/kokkos#5070]
# Statement 

- [x] 2.1
  - explore current setup of testing 
  - choose one Kokkos Core performance test and one Kokkos Kernels tests as design vehicle
     -  propose and justify which tests should be used 
  - figure out a plan for how we deal with googlebench dependency 
  - figure out which compilers/backends we want to run all perf tests with 
  - for more details, see #5342
- [x] 2.2 
   - Design metadata context to store system config, toolchain details etc.
  - includes for example the information from Kokkos::print configuration
  - explore integration of Kokkos tools metadata declaration
  - for more details, see #5348 
- [x] 2.3 Add metadata output to design vehicle performance tests
  - whatever comes out of `2.2`, just use `benchmark` API `benchmark::AddCustomContext(const std::string& key, const std::string& value)` to include the metadata context in the output
- [x] 2.4 After design is fully approved convert the bulk of the performance tests in the Kokkos Core repository
  - src/perf_test, containers/performance tests
- [x] 2.5 Propose a mechanism to track performance over time
  - needs to be able to produce timelines specific to system config and toolchain
  - What we already decided: 
    - to have a repo inside the kokkos organization where to store all the json files: let's call this the `database-repo` for now 
    - to push there (somehow) all the json files generated by the benchmark for example every time a PR is merged into main branch 
    - to have a script inside `database-repo` that automatically generates plots every time files are updated,
    - for more details, see #5464 
- [x] 2.6 Implement agreed upon tracking mechanism

**Comment by cz4rs** [comment]
Updating the issue for FY23.

**Comment by cz4rs** [comment]
List of candidates for automated benchmarking:
- algorithms (`kokkos/algorithms`)
  - extensive unit tests exist, but no perf tests/benchmarks
  - non-parallel `std` versions could be used for performance baseline (they are already executed in a lot of unit tests to ensure valid results)
- containers (`kokkos/containers/performance/tests`)
- anything from `kokkos/benchmarks`, `kokkos/benchmarks/benchmark_suite`, for example `miniMD`, `miniFE` (?)
  - those might not be "microbenchmarks" (which Google benchmark lib is optimized for), but we could still force them to store results in compatible JSON format
- it could be interesting to measure performance of the very basic `parallel_for`, `parallel_reduce` etc. and compare them with native implementations for certain backends - to verify how much overhead Kokkos introduces

**Comment by cz4rs** [comment]
The bulk of the existing benchmarks in Kokkos Core was converted. See https://github.com/kokkos/kokkos-benchmark-results for (continuously added) benchmark results and https://github.com/kokkos/kokkos/pull/5886 for proposed follow-up on Kokkos algorithms.
