### ISSUE TITLE
Clang-Tidy bugprone-* checks tracker

### ISSUE THREAD

**Issue by dalg24** [kokkos/kokkos#7575]
Following up after the merge of #7572 
Here is the list of bugprone-* checks currently disabled.
I don't anticipate we necessarily can/want fix all of them but I want an easy way to keep track of what has been done.
If you are working on any of them, please write down your name on the line and replace it with a reference to the PR when it is up.

  - [ ] bugprone-assignment-in-if-condition,
  - [ ] bugprone-branch-clone,
  - [ ] bugprone-crtp-constructor-accessibility,
  - [ ] bugprone-easily-swappable-parameters,
  - [ ] bugprone-empty-catch,
  - [ ] bugprone-exception-escape,
  - [ ] bugprone-inc-dec-in-conditions,
  - [ ] bugprone-integer-division,
  - [ ] bugprone-macro-parentheses,
  - [ ] bugprone-misplaced-widening-cast,
  - [ ] bugprone-multi-level-implicit-pointer-conversion,
  - [ ] bugprone-narrowing-conversions,
  - [ ] bugprone-non-zero-enum-to-bool-conversion,
  - [ ] bugprone-reserved-identifier,
  - [ ] bugprone-return-const-ref-from-parameter,
  - [ ] bugprone-signed-char-misuse,
  - [ ] bugprone-sizeof-expression,
  - [ ] bugprone-suspicious-include,
  - [ ] bugprone-suspicious-memory-comparison,
  - [ ] bugprone-suspicious-string-compare,
  - [ ] bugprone-switch-missing-default-case,
  - [ ] bugprone-throw-keyword-missing,
  - [ ] bugprone-unchecked-optional-access,
  - [ ] bugprone-undefined-memory-manipulation,
  - [ ] bugprone-unhandled-exception-at-new,
  - [ ] bugprone-unhandled-self-assignment,
  - [ ] bugprone-unused-raii,
  - [ ] bugprone-use-after-move,
